branch-defaults:
  default:
    environment: journey-server-dev2
    group_suffix: null
environment-defaults:
  journey-dev:
    branch: null
    repository: null
global:
  application_name: journey-server
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 17.03.1-ce
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
